### PR TITLE
Create translation for Russian language

### PR DESCRIPTION
**Pull request by Kutikov**
I can create whole translation for Russian and Ukrainian langs

### CODE REVIEW

**Comment by Kutikov** [comment]
In frontend/locales/loc/translation.json what will I translate in next lines???
` "calendarFormat" : {
      "lastDay" : "[Yesterday at] LTS",
      "sameDay" : "[Today at] LTS",
      "nextDay" : "[Tomorrow at] LTS",
      "lastWeek" : "[last] dddd [at] LTS",
      "nextWeek" : "dddd [at] LTS",
      "sameElse" : "L"
    },`

**Comment by Kutikov** [comment]
I think I've done with translating. Not found landing page strings, sorry

**Comment by pschlan** [comment]
Thanks so much, this is great!

Could you also add ru to statuspage/src/App.jsx?

> In frontend/locales/loc/translation.json what will I translate in next lines???
> 
> ```
> "calendarFormat" : {
>       "lastDay" : "[Yesterday at] LTS",
>       "sameDay" : "[Today at] LTS",
>       "nextDay" : "[Tomorrow at] LTS",
>       "lastWeek" : "[last] dddd [at] LTS",
>       "nextWeek" : "dddd [at] LTS",
>       "sameElse" : "L"
>     },
> ```

Here, you only need to translate text in square brackets `[]`. The other chars are format specifiers for moment.js, see https://momentjs.com/

**Comment by Kutikov** [comment]
All done. I've problem with adition due to lack of normal internet in Ukraine. So it is placed in another pull request

**Comment by pschlan** [comment]
Merged. Thanks again!

**Comment by pschlan** [comment]
Deployed to prod now 🚀. Thanks again!

**Pull request merged**
