### PR TITLE
Added lang es

### PR DESCRIPTION
**Pull request by wuniversales**

### CODE REVIEW

**Comment by wuniversales** [comment]
I'm working on it, please wait, I'll tell you when it's ready :)

**Comment by pschlan** [comment]
Cool stuff, let me know when it is ready :) Looking forward to it.

**Comment by pschlan** [comment]
Are you still working on this?

**Comment by pschlan** [comment]
Closing due to inactivity. In case you continue to work on this (which would be highly appreciated, of course), feel free to re-open.

**Comment by wuniversales** [comment]
Hello, I'm sorry, lately I don't have time for anything, if someone can continue with the translation I would appreciate it. :)

**Pull request closed without merging**
